name: nix-bundle arknights-mower
on: [ push ]

jobs:
  nix-bundle:
    runs-on: ubuntu-latest
    env:
      CMD: nix-bundle "(pkgs.callPackage ./. { }).arknights-mower" /bin/arknights-mower

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell nix-scripts/bundle-am.nix
