name: nix-bundle arknights-mower
on: [ push ]

#   push:
#     paths:
#       - 'pkgs/arknights-mower'

jobs:
  nix-bundle:
    runs-on: ubuntu-latest

    env:
      CH_URL: https://nixos.org/channels/nixos-21.11

    strategy:
      matrix:
        container: [
            "nixos/nix:latest-amd64",
            "nixos/nix:latest-arm64"
        ]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - run: nix-channel --add $CH_URL nixpkgs
      - run: nix-channel --update
      - run: nix-shell nix-scripts/bundle-am.nix

      - uses: actions/upload-artifact@v2
        with:
          path: arknights-mower
